export const dummyRooms = [
  {
    id: 1,
    name: "Deluxe Room 101",
    type: "Deluxe",
    branch: "Kathmandu Branch",
    pricePerNight: 3500,
    capacity: 2,
    size: "28 sqm",
    available: true,
    description: "A spacious and elegantly designed room featuring a king-size bed, city view, and modern amenities for a comfortable stay.",
    amenities: [
      { icon: "Wifi", label: "Free WiFi" },
      { icon: "Coffee", label: "Complimentary Breakfast" },
      { icon: "Tv", label: "Smart TV" },
      { icon: "Wind", label: "Air Conditioning" },
    ],
    images: ["", "", ""],
  },
  {
    id: 2,
    name: "Executive Suite 201",
    type: "Suite",
    branch: "Pokhara Branch",
    pricePerNight: 6500,
    capacity: 4,
    size: "45 sqm",
    available: false,
    description: "Luxurious suite with mountain view, separate living area, and premium amenities.",
    amenities: [
      { icon: "Wifi", label: "Free WiFi" },
      { icon: "Coffee", label: "Complimentary Breakfast" },
      { icon: "Tv", label: "Smart TV" },
      { icon: "Wind", label: "Air Conditioning" },
    ],
    images: ["", "", ""],
  },
  {
    id: 3,
    name: "Standard Room 102",
    type: "Standard",
    branch: "Chitwan Branch",
    pricePerNight: 2200,
    capacity: 2,
    size: "20 sqm",
    available: true,
    description: "Comfortable standard room with all basic amenities for a pleasant stay.",
    amenities: [
      { icon: "Wifi", label: "Free WiFi" },
      { icon: "Tv", label: "Smart TV" },
      { icon: "Wind", label: "Air Conditioning" },
    ],
    images: ["", "", ""],
  },
];